# These are supported funding model platforms

# GitHub Sponsors
# github: [task2earn]

# Cardano Address for ADA donations
custom: 
  - "ADA Address: addr1_task2earn_donations"
  - "Email for commercial licensing: danamphred@gmail.com"

# Note: This project is licensed under CC BY-NC 4.0 (non-commercial)
# For commercial use, please contact us for licensing options

